$background = 040303
$onBackground = f5e0e6
$surface = 040303
$surfaceDim = 040303
$surfaceBright = 120b0d
$surfaceContainerLowest = 000000
$surfaceContainerLow = 070305
$surfaceContainer = 0a0507
$surfaceContainerHigh = 0d070a
$surfaceContainerHighest = 10090c
$onSurface = f5e0e6
$surfaceVariant = 10090c
$onSurfaceVariant = b9a6ac
$outline = 827176
$outlineVariant = 524449
$inverseSurface = fff8f8
$inverseOnSurface = 5c5355
$shadow = 000000
$scrim = 000000
$surfaceTint = 35232a
$primary = f0b7cd
$primaryDim = e1a9bf
$onPrimary = 5c3345
$primaryContainer = 714558
$onPrimaryContainer = ffd9e6
$inversePrimary = 7f5165
$primaryFixed = ffc4db
$primaryFixedDim = f0b7cd
$onPrimaryFixed = 512a3b
$onPrimaryFixedVariant = 714558
$secondary = e1bdc9
$secondaryDim = d2b0bc
$onSecondary = 523943
$secondaryContainer = 4d343e
$onSecondaryContainer = d9b6c2
$secondaryFixed = fed9e5
$secondaryFixedDim = efcbd7
$onSecondaryFixed = 513842
$onSecondaryFixedVariant = 70545e
$tertiary = fde3ff
$tertiaryDim = f6d0fd
$onTertiary = 6a4c72
$tertiaryContainer = f6d0fd
$onTertiaryContainer = 614469
$tertiaryFixed = f6d0fd
$tertiaryFixedDim = e8c3ef
$onTertiaryFixed = 4d3155
$onTertiaryFixedVariant = 6b4d73
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = 9a697d
$secondaryPaletteKeyColor = 8d6f7a
$tertiaryPaletteKeyColor = 8c6c94
$neutralPaletteKeyColor = 7e7477
$neutralVariantPaletteKeyColor = 837378
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = 9a697d
$secondary_paletteKeyColor = 8d6f7a
$tertiary_paletteKeyColor = 8c6c94
$neutral_paletteKeyColor = 7e7477
$neutral_variant_paletteKeyColor = 837378
$term0 = 080808
$term1 = ff4995
$term2 = ffbabb
$term3 = ffdee0
$term4 = b3a2d5
$term5 = e790b6
$term6 = ffba93
$term7 = eed1d3
$term8 = b39ea0
$term9 = ff7fab
$term10 = ffd3d2
$term11 = fff1f1
$term12 = babfdd
$term13 = f7a8c6
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffedf0
$flamingo = fbd9e2
$pink = ffd0e4
$mauve = fca5da
$red = fa95be
$maroon = f1aac3
$peach = ffbcc9
$yellow = ffeded
$green = ffd8c5
$teal = dedcff
$sky = ebd1ff
$sapphire = f2b2f2
$blue = f0a4e3
$lavender = fcb8e9
$klink = b46fb1
$klinkSelection = b46fb1
$kvisited = c25d9b
$kvisitedSelection = c25d9c
$knegative = e64f90
$knegativeSelection = e64f91
$kneutral = ff84a4
$kneutralSelection = ff84a4
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f5e0e6
$subtext1 = b9a6ac
$subtext0 = 827176
$overlay2 = 1a1818
$overlay1 = 171516
$overlay0 = 141313
$surface2 = 100f0f
$surface1 = 0c0a0b
$surface0 = 050404
$base = 010000
$mantle = 010000
$crust = 010000
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
