#########################
#####   AUTOSTART   #####
#########################

# Wallpaper
exec-once = waypaper --restore

# Load Hyprland plugins
exec-once = hyprpm reload

# Telegram
exec-once = ayugram-desktop -autostart

# Sudo for gui
exec-once = systemctl --user start hyprpolkitagent

# Notification daemon
exec-once = killall dunst && killall mako && swaync

# Keyboard event popups (Brightnress and volume changes)
exec-once = swayosd-server

# Clipboard manager
exec-once = wl-paste --watch clipvault store

# Mirror Android notifications
exec-once = a2ln

# Launch terminal on boot
exec-once = kitty

# Handmade scripts
exec-once = ~/.config/scripts/battery_notification.sh
exec-once = ~/.config/scripts/language_notification.sh

# Vivaldi notifications
exec-once = [silent] vivaldi-stable --no-startup-window --disable-gpu --ozone-platform=wayland

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start hyprland-session.target
exec-once = waybar
