####################################################
###################   MONITORS   ###################
### https://wiki.hypr.land/Configuring/Monitors ####
####################################################

monitorv2 {
    output = eDP-1
    mode = 1920x1080x165
    position = 0x0
}

monitorv2 {
    output = HDMI-A-1
    mode = 1920x1080x60
    position = 1920x-350
}
