######################################
#####   WINDOWS AND WORKSPACES   #####
######################################

windowrule {
    name = ignore-maximize-requests
    suppress_event = maximize
    match:class = .*
}

windowrule {
    name = fix-dragging
    no_focus = on
    match:class = ^$
    match:title = ^$
    match:xwayland = 1
    match:float = 1
    match:fullscreen = 0
    match:pin = 0
}

windowrule {
    name = picture-in-picture
    match:title = ^(Picture-in-Picture)$
    float = on
    pin = on
    move = 75% 75%
    size = 20% 20%
}

windowrule {
    name = transparent-apps
    match:class = ^(v2rayN|org.prismlauncher.PrismLauncher)$
    opacity = 0.95
}

windowrule {
    name = force-tiling
    match:class = ^(org.prismlauncher.PrismLauncher|steam)$
    float = false
}

# 1) Steam client main window
windowrule {
    name = steam-client
    match:class = Steam
    float = off
    maximize = on
}

# 2) Steam overlay / game windows that sometimes float (match by title regex)
windowrule {
    name = steam-game-windows
    match:class = Steam
    match:title = .* - Steam
    float = off
    fullscreen = on
}

layerrule {
    name = swaync-blur
    match:namespace = ^(swaync-control-center|swaync-notification-window|rofi)$
    blur = on
}

layerrule {
    name = rofi-blur
    match:namespace = rofi
    blur = true
    ignore_alpha = 0.5
}

windowrule {
    name = hyprpaper-we
    match:class = ^(HyprPaper-WE-Window)$
    workspace = special silent
    no_focus = on
    no_anim = on
    rounding = 0
}


# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds>
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}
