# VPN
bind = $mainMod, K, togglespecialworkspace, VPN
exec-once = [workspace special:VPN silent] koala-clash
windowrule {
    name = special-workspace-vpn
    workspace = special:VPN silent
    match:class = ^(koala-clash)$
}

# Telegram
bind = $mainMod, A, togglespecialworkspace, Telegram
exec-once = [workspace special:Telegram silent] ayugram-desktop
windowrule {
    name = special-workspace-telegram
    workspace = special:Telegram silent
    match:class = ^(com.ayugram.desktop)$
}

# YouTube Music
bind = $mainMod, M, togglespecialworkspace, Music
exec-once = [workspace special:Music silent] /usr/lib/floorp/floorp --name floorp-7f02dd01-11e3-4e54-b657-acc951604c87 --profile /home/mrboomdev/.floorp/p2503pa8.default-default --start-ssb "{7f02dd01-11e3-4e54-b657-acc951604c87}"
windowrule {
    name = special-workspace-music
    workspace = special:Music silent
    match:class = ^(floorp-7f02dd01-11e3-4e54-b657-acc951604c87)$
}